#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kerby
Version  : 1.0.1
Release  : 1
URL      : https://github.com/apache/directory-kerby/archive/kerby-all-1.0.1.tar.gz
Source0  : https://github.com/apache/directory-kerby/archive/kerby-all-1.0.1.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar
Source2  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.pom
Source3  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar
Source4  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.pom
Source5  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar
Source6  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.pom
Source7  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar
Source8  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.pom
Source9  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar
Source10  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.pom
Source11  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar
Source12  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.pom
Source13  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar
Source14  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.pom
Source15  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar
Source16  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.pom
Source17  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar
Source18  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.pom
Source19  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-all/1.0.1/kerby-all-1.0.1.pom
Source20  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar
Source21  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.pom
Source22  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-common/1.0.1/kerby-common-1.0.1.pom
Source23  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar
Source24  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.pom
Source25  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar
Source26  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.pom
Source27  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-provider/1.0.1/kerby-provider-1.0.1.pom
Source28  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar
Source29  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.pom
Source30  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar
Source31  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.pom
Source32  : https://repo1.maven.org/maven2/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar
Source33  : https://repo1.maven.org/maven2/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 Public-Domain
Requires: mvn-kerby-data = %{version}-%{release}

%description
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

%package data
Summary: data components for the mvn-kerby package.
Group: Data

%description data
data components for the mvn-kerby package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1/kerby-all-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1/kerby-common-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1/kerby-provider-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.pom
