#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-kerby
Version  : 1.0.1
Release  : 8
URL      : https://github.com/apache/directory-kerby/archive/kerby-all-1.0.1.tar.gz
Source0  : https://github.com/apache/directory-kerby/archive/kerby-all-1.0.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.pom
Source5  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.jar
Source6  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.pom
Source7  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.jar
Source8  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.pom
Source9  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.jar
Source10  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.pom
Source11  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.jar
Source12  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.pom
Source13  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.jar
Source14  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.pom
Source15  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.jar
Source16  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.pom
Source17  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.jar
Source18  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.pom
Source19  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-all/1.1.0/kerby-all-1.1.0.pom
Source20  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.jar
Source21  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.pom
Source22  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-common/1.1.0/kerby-common-1.1.0.pom
Source23  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.jar
Source24  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.pom
Source25  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-kerb/1.0.1/kerby-kerb-1.0.1.pom
Source26  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-kerb/1.1.0/kerby-kerb-1.1.0.pom
Source27  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-kerb/1.1.1/kerby-kerb-1.1.1.pom
Source28  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.jar
Source29  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.pom
Source30  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-provider/1.1.0/kerby-provider-1.1.0.pom
Source31  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.jar
Source32  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.pom
Source33  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.jar
Source34  : https://repo.maven.apache.org/maven2/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.pom
Source35  : https://repo.maven.apache.org/maven2/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.jar
Source36  : https://repo.maven.apache.org/maven2/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.pom
Source37  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar
Source38  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.pom
Source39  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar
Source40  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.pom
Source41  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar
Source42  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.pom
Source43  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar
Source44  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.pom
Source45  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar
Source46  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.pom
Source47  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar
Source48  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.pom
Source49  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar
Source50  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.pom
Source51  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar
Source52  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.pom
Source53  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar
Source54  : https://repo1.maven.org/maven2/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.pom
Source55  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-all/1.0.1/kerby-all-1.0.1.pom
Source56  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar
Source57  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.pom
Source58  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-common/1.0.1/kerby-common-1.0.1.pom
Source59  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar
Source60  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.pom
Source61  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar
Source62  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.pom
Source63  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-provider/1.0.1/kerby-provider-1.0.1.pom
Source64  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar
Source65  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.pom
Source66  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar
Source67  : https://repo1.maven.org/maven2/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.pom
Source68  : https://repo1.maven.org/maven2/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar
Source69  : https://repo1.maven.org/maven2/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT Public-Domain
Requires: mvn-kerby-data = %{version}-%{release}
Requires: mvn-kerby-license = %{version}-%{release}

%description
<!--
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

%package data
Summary: data components for the mvn-kerby package.
Group: Data

%description data
data components for the mvn-kerby package.


%package license
Summary: license components for the mvn-kerby package.
Group: Default

%description license
license components for the mvn-kerby package.


%prep
%setup -q -n directory-kerby-kerby-all-1.0.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-kerby
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-kerby/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-kerby/NOTICE
cp kerby-dist/kdc-dist/LICENSE %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_LICENSE
cp kerby-dist/kdc-dist/licenses/LICENSE-slf4j.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE-slf4j.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.base64.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.base64.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.jbzip2.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jbzip2.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.jfastlz.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jfastlz.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.jsr166y.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jsr166y.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.libdivsufsort.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.libdivsufsort.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.protobuf.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.protobuf.txt
cp kerby-dist/kdc-dist/licenses/LICENSE.webbit.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.webbit.txt
cp kerby-dist/tool-dist/LICENSE %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_LICENSE
cp kerby-dist/tool-dist/NOTICE %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_NOTICE
cp kerby-dist/tool-dist/licenses/LICENSE-slf4j.txt %{buildroot}/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_licenses_LICENSE-slf4j.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.1.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.1.0/kerby-all-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.1.0
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.1.0/kerby-common-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.0.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.0.1/kerby-kerb-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.0
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.0/kerby-kerb-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.1
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.1/kerby-kerb-1.1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.1.0
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.1.0/kerby-provider-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1/kerby-all-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1/kerby-common-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1/kerby-provider-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.0.1/kerb-admin-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-admin/1.1.0/kerb-admin-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.0.1/kerb-client-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-client/1.1.0/kerb-client-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.0.1/kerb-common-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-common/1.1.0/kerb-common-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.0.1/kerb-core-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-core/1.1.0/kerb-core-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.0.1/kerb-crypto-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-crypto/1.1.0/kerb-crypto-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.0.1/kerb-identity-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-identity/1.1.0/kerb-identity-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.0.1/kerb-server-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-server/1.1.0/kerb-server-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.0.1/kerb-simplekdc-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-simplekdc/1.1.0/kerb-simplekdc-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.0.1/kerb-util-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerb-util/1.1.0/kerb-util-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.0.1/kerby-all-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-all/1.1.0/kerby-all-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.0.1/kerby-asn1-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-asn1/1.1.0/kerby-asn1-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.0.1/kerby-common-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-common/1.1.0/kerby-common-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.0.1/kerby-config-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-config/1.1.0/kerby-config-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.0.1/kerby-kerb-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.0/kerby-kerb-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-kerb/1.1.1/kerby-kerb-1.1.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.0.1/kerby-pkix-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-pkix/1.1.0/kerby-pkix-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.0.1/kerby-provider-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-provider/1.1.0/kerby-provider-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.0.1/kerby-util-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-util/1.1.0/kerby-util-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.0.1/kerby-xdr-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/kerby-xdr/1.1.0/kerby-xdr-1.1.0.pom
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.0.1/token-provider-1.0.1.pom
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.jar
/usr/share/java/.m2/repository/org/apache/kerby/token-provider/1.1.0/token-provider-1.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-kerby/LICENSE
/usr/share/package-licenses/mvn-kerby/NOTICE
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_LICENSE
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE-slf4j.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.base64.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jbzip2.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jfastlz.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.jsr166y.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.libdivsufsort.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.protobuf.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_kdc-dist_licenses_LICENSE.webbit.txt
/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_LICENSE
/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_NOTICE
/usr/share/package-licenses/mvn-kerby/kerby-dist_tool-dist_licenses_LICENSE-slf4j.txt
